services:
  dicebot:
    image: ghcr.io/the-may/telegram_dicebot:latest
    container_name: telegram_dicebot
    restart: unless-stopped
    env_file:
      - .env
    #using this label with Watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

